### ISSUE TITLE
Using classes instead of element in Css

### ISSUE THREAD

**Issue by ghost** [asgore-undertale/RenovArabi.github.io#1]
Hi Asgor :3

Very interesting editor indeed, but some CSS needs to be intact.

I will look after it in a fork

![image](https://user-images.githubusercontent.com/37517008/208263533-7d279157-a5ee-4393-b9e9-aca3f34b3c19.png)

**Comment by ghost** [comment]
https://chipsum.github.io/RenovArabi/

**Comment by asgore-undertale** [comment]
Hi Chipsum
Thanks a lot for your help and suggestions <3
Gonna see your work and edit my scripts :like_emoji:
